

export const LOGIN_REQUEST_PENDING = "SIGN_REQUEST_PENDING";
export const LOGIN_REQUEST_FAILURE = "SIGN_REQUEST_FAILURE";
export const LOGIN_REQUEST_SUCCESS = "SIGN_REQUEST_SUCCESS";
export const LOGOUT="LOGOUT"